name: Paddle Booking Automation

on:
  workflow_dispatch:

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chromium
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser

      - name: Set up Xvfb (Virtual Display)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Run Paddle Booking Automation
        env:
          DISPLAY: :99
        run: |
          python /home/runner/work/PaddleBot/PaddleBot/paddle/main.py
