name: Tennis Court Reservation Automation

on:
  workflow_dispatch:  # Manual trigger with inputs
    inputs:
      timeslot:
        description: 'Time slot to book (e.g. 17:00 or 18:00)'
        required: true
        type: choice
        options:
          - "17:00"
          - "6:00"
      days_in_advance:
        description: 'Days in advance to book'
        required: true
        type: choice
        options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"

jobs:
  book-courts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pyyaml

      - name: Run tennis reservation system (headless)
        run: |
          cd tennis
          python main.py --timeslot "${{ github.event.inputs.timeslot }}" --days-advance "${{ github.event.inputs.days_in_advance }}"
        env:
          CI: "true"
          HEADLESS: "true"

      - name: Upload logs as artifacts
        if: always()  # Run even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: reservation-logs
          path: |
            tennis/reservations.log
            tennis/screenshots/*.png