name: Tennis Court Reservation Automation

on:
  workflow_dispatch:  # Manual trigger with inputs
    inputs:
      username:
        description: 'Username for booking (leave empty to book 3 default courts)'
        required: false
        type: string
      court:
        description: 'Court number (leave empty to book 3 default courts)'
        required: false
        type: string
      timeslot:
        description: 'Time slot (e.g. 17:30, leave empty to book 3 default courts)'
        required: false
        type: string
      days_in_advance:
        description: 'Days in advance to book (leave empty to book 3 default courts)'
        required: false
        type: string

jobs:
  book-courts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pyyaml

      - name: Install Chromium and related tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y xvfb

      - name: Set up virtual display
        run: |
          Xvfb :99 -ac &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tennis reservation system
        run: |
          cd tennis
          python main.py --court "${{ github.event.inputs.court }}" --username "${{ github.event.inputs.username }}" --timeslot "${{ github.event.inputs.timeslot }}" --days-advance "${{ github.event.inputs.days_in_advance }}"
        env:
          CI: "true"

      - name: Upload logs as artifacts
        if: always()  # Run even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: reservation-logs
          path: |
            tennis/reservations.log
            tennis/screenshots/*.png